version: "3"

services:

  navidrome:
    image: deluan/navidrome:latest
    container_name: navi
    user: "1000:1000" 
    restart: unless-stopped
    ports:
      - "8200:4533"
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
    volumes:
      - ./data:/data
      - ./music:/music:ro
